name: Fetch posts

on:
  schedule:
    - cron: "0 2-14 * * *" # update everyday at 10AM-10PM (TW time)

jobs:
  fetch_posts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Fetch posts
        env:
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        run: |
          cd pipeline
          pip3 install -r requirements.txt
          python3 fetch_posts.py
          python3 index.py
      - name: Commit and push
        run: |
          git config --global user.name 'Fetch Bot'
          git config --global user.email 'noreply@na.com'
          git add pipeline/posts
          git commit -m "Fetch posts" || true
          git push
