name: fetch posts

on:
  schedule:
    - cron: "0 2-14 * * *" # update everyday at 10AM-10PM (TW time)

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Fetch posts
        run: |
          pip3 install -r requirements.txt
          python3 fetch_data.py ${{ secrets.ALGOLIA_API_KEY }}
          python3 offline_process.py
      - name: Commit and push
        run: |
          git config --global user.name 'Fetch Bot'
          git config --global user.email 'noreply@na.com'
          git add docs/_posts
          git commit -m "Fetch posts" || true
          git push
